version: "3"
services:
  db:
    image: postgres:10
    # volumes: 10.142.0.7
    #   - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5446:5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata

  web:
    image: odoo:13.0
    
    depends_on:
      - db
    ports:
      - "11500:8069"
    
    volumes:
      - ./o_addons:/mnt/extra-addons
      - ./o_etc:/etc/odoo
volumes:
  db:
  odoo10:
  
