version: "2"
services:
  db:
    # image: postgres:9.5
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "11002:5432"

  odoo10:
    # image: odoo:11.0
    # build: ./
    image: victoralin10/odoo10:latest
    depends_on:
      - db
    ports:
      - "11000:8069"
    tty: true
    command: -- --dev=reload
    #    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./o_addons:/mnt/extra-addons
      - ./o_etc:/etc/odoo
volumes:
  db:
  odoo10:
